import test from 'node:test';
import assert from 'node:assert/strict';
import {loadContent,parseProject,markdown} from '../src/lib/content.mjs';
import {href,esc,home,resume,education,projectStart} from '../src/lib/render.mjs';
const {profile,projects,config}=await loadContent();const data=projects.map(p=>p.data);
test('Project identifiers and ordering are unique',()=>{assert.equal(new Set(data.map(x=>x.id)).size,data.length);assert.equal(new Set(data.map(x=>x.order)).size,data.length);assert.ok(data.every((x,i)=>i===0||data[i-1].order<x.order));});
test('Public identity is correct',()=>{assert.equal(profile.name,'정유빈');assert.equal(profile.email,'jyb1018@gmail.com');assert.equal(profile.school,'건국대학교');});
test('Graduation rendering follows the explicit profile value',()=>{if(profile.graduationYear===null){assert.match(education(profile),/재학/);assert.doesNotMatch(education(profile),/졸업예정/);}else{assert.ok(education(profile).includes(`${profile.graduationYear}년 ${profile.graduationMonth}월 졸업예정`));}});
test('Confirmed graduation year can be displayed',()=>assert.match(education({...profile,graduationYear:2030,graduationMonth:null}),/2030년 졸업예정/));
test('Three work repositories remain private',()=>data.slice(0,3).forEach(p=>{assert.equal(p.visibility,'private');assert.equal(p.url,null);}));
test('Only the verified public project is linked',()=>{assert.equal(data.filter(p=>p.url).length,1);assert.equal(data.at(-1).url,'https://github.com/jyb1018/AI-Development-harness');});
test('Project-site and custom-domain paths',()=>{assert.equal(href({base:'/portfolio'},'resume.pdf'),'/portfolio/resume.pdf');assert.equal(href({base:'/'},'resume.pdf'),'/resume.pdf');assert.equal(href({base:'/new/'},'projects/a/'),'/new/projects/a/');});
test('Invalid base paths are rejected',()=>{assert.throws(()=>href({base:'../escape'}));assert.throws(()=>href({base:'/../escape'}));});
test('HTML strings are escaped',()=>assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('All current MDX content exports through the portable path',()=>projects.forEach(p=>assert.match(markdown(p.body),/<h2/)));
test('Markdown renderer fails rather than pretending to support JSX',()=>assert.throws(()=>markdown('import A from "a";\n<A />')));
test('Bad frontmatter is rejected',()=>assert.throws(()=>parseProject('---\nhello\n---\nBody')));
test('Private repository URL is rejected',()=>assert.throws(()=>parseProject('---\n'+JSON.stringify({...data[0],url:'https://github.com/jyb1018/example'})+'\n---\nBody')));
test('Home and resume use all five project summaries',()=>{for(const d of data){assert.ok(home(profile,data,config).includes(d.title));assert.ok(resume(profile,data,config).includes(d.resume.action));}});
test('Operating metrics have the correct scope',()=>{const m=data.find(x=>x.id==='monitorcontrol');assert.ok(m.outcome.includes(`${profile.metrics[1].value}개 매장`));assert.ok(m.resume.result.includes(`${profile.metrics[2].value}대`));assert.match(m.resume.result,/한 매장/);});
test('Case pages cannot leak a private GitHub URL',()=>data.slice(0,4).forEach(d=>assert.doesNotMatch(projectStart(profile,d,config),/github\.com\/[^"<]+\/(?:PokerOS|PokerPlus|MonitorControl)/)));
test('Resume is planned as exactly two printable pages',()=>assert.equal((resume(profile,data,config).match(/class="resume-page"/g)||[]).length,2));
test('Primary routes and contact links are present',()=>{const html=home(profile,data,config);assert.match(html,/id="projects"/);assert.match(html,/mailto:jyb1018@gmail.com/);assert.match(html,/download="정유빈_이력서.pdf"/);});
test('Confirmed February 2027 graduation appears on home and resume',()=>{for(const h of [home(profile,data,config),resume(profile,data,config)])assert.match(h,/2027년 2월 졸업예정/);});
